[project]
name = "odoo-addons-oca-event"
version = "18.0.20260322.0"
dependencies = [
    "odoo-addon-event_contact==18.0.*",
    "odoo-addon-event_mail==18.0.*",
    "odoo-addon-event_min_seat==18.0.*",
    "odoo-addon-event_registration_cancel_reason==18.0.*",
    "odoo-addon-event_registration_mass_mailing==18.0.*",
    "odoo-addon-event_registration_multi_qty==18.0.*",
    "odoo-addon-event_registration_partner_unique==18.0.*",
    "odoo-addon-event_sale_free_no_invoiceable==18.0.*",
    "odoo-addon-event_sale_registration_multi_qty==18.0.*",
    "odoo-addon-event_sale_session==18.0.*",
    "odoo-addon-event_session==18.0.*",
    "odoo-addon-event_session_registration_multi_qty==18.0.*",
    "odoo-addon-partner_event==18.0.*",
    "odoo-addon-website_event_contact==18.0.*",
    "odoo-addon-website_event_filter_city==18.0.*",
    "odoo-addon-website_event_membership_restriction==18.0.*",
    "odoo-addon-website_event_questions_by_ticket==18.0.*",
    "odoo-addon-website_event_require_legal==18.0.*",
    "odoo-addon-website_event_require_login==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
